### ISSUE TITLE
库环境可以分享一下吗

### ISSUE THREAD

**Issue by CJLUHLL** [Lizonghang/AGOD#2]
库环境可以分享一下吗

**Comment by Lizonghang** [comment]
你好，可以参考下这个Dockerfile：

https://github.com/Lizonghang/AGOD/blob/main/docker/Dockerfile

**Comment by CJLUHLL** [comment]
我照着里面的信息安装环境了 但是运行main.py的时候tianshou库报错了

Environment Name: AaaS
Algorithm Name: DiffusionSAC
Shape of Observation Space: 42
Shape of Action Space: 20
Epoch #1: 1000it [00:40, 24.88it/s, env_step=1000, len=0, loss/critic=4.387, n/ep=0, n/st=1000, overall_loss=-1.196, rew=0.00]                   
Epoch #1: test_reward: -999.603662 ± 0.000000, best_reward: -122.407333 ± 0.000000 in #0
{'best_result': '-122.41 ± 0.00',
 'best_reward': -122.4073327681062,
 'duration': '52.00s',
 'test_episode': 2,
 'test_speed': '171.44 step/s',
 'test_step': 2002,
 'test_time': '11.68s',
 'train_episode': 0,
 'train_speed': '24.80 step/s',
 'train_step': 1000,
 'train_time/collector': '7.13s',
 'train_time/model': '33.20s'}
Traceback (most recent call last):
  File "/home/find-jinglin/LLM-Model/model_file/AGOD-main/main.py", line 204, in <module>
    main(get_args())
  File "/home/find-jinglin/LLM-Model/model_file/AGOD-main/main.py", line 198, in main
    result = collector.collect(n_episode=1, render=args.render)
  File "/home/find-jinglin/enter/envs/god/lib/python3.9/site-packages/tianshou/data/collector.py", line 263, in collect
    self.data = self.data[:min(self.env_num, n_episode)]
  File "/home/find-jinglin/enter/envs/god/lib/python3.9/site-packages/tianshou/data/batch.py", line 245, in __getitem__
    new_batch.__dict__[batch_key] = obj[index]
  File "/home/find-jinglin/enter/envs/god/lib/python3.9/site-packages/tianshou/data/batch.py", line 245, in __getitem__
    new_batch.__dict__[batch_key] = obj[index]
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

**Comment by CJLUHLL** [comment]
问题: IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
描述
运行 AGOD-main 仓库中的 main.py 脚本时遇到了 IndexError 错误。以下是详细信息：
复现步骤
克隆仓库并进入 AGOD-main 目录。
使用以下命令运行 main.py 脚本：
python /path/to/AGOD-main/main.py
错误信息
Environment Name: AaaS
Algorithm Name: DiffusionSAC
Shape of Observation Space: 42
Shape of Action Space: 20
Epoch #1: 1000it [00:40, 24.88it/s, env_step=1000, len=0, loss/critic=4.387, n/ep=0, n/st=1000, overall_loss=-1.196, rew=0.00]                   
Epoch #1: test_reward: -999.603662 ± 0.000000, best_reward: -122.407333 ± 0.000000 in #0
{'best_result': '-122.41 ± 0.00',
 'best_reward': -122.4073327681062,
 'duration': '52.00s',
 'test_episode': 2,
 'test_speed': '171.44 step/s',
 'test_step': 2002,
 'test_time': '11.68s',
 'train_episode': 0,
 'train_speed': '24.80 step/s',
 'train_step': 1000,
 'train_time/collector': '7.13s',
 'train_time/model': '33.20s'}
Traceback (most recent call last):
  File "/path/to/AGOD-main/main.py", line 204, in <module>
    main(get_args())
  File "/path/to/AGOD-main/main.py", line 198, in main
    result = collector.collect(n_episode=1, render=args.render)
  File "/path/to/envs/god/lib/python3.9/site-packages/tianshou/data/collector.py", line 263, in collect
    self.data = self.data[:min(self.env_num, n_episode)]
  File "/path/to/envs/god/lib/python3.9/site-packages/tianshou/data/batch.py", line 245, in __getitem__
    new_batch.__dict__[batch_key] = obj[index]
  File "/path/to/envs/god/lib/python3.9/site-packages/tianshou/data/batch.py", line 245, in __getitem__
    new_batch.__dict__[batch_key] = obj[index]
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
相关代码
# main.py，第198行
result = collector.collect(n_episode=1, render=args.render)

# tianshou/data/collector.py，第263行
self.data = self.data[:min(self.env_num, n_episode)]

环境信息
Python 版本: 3.9
Tianshou 版本: 0.4.10

**Comment by Lizonghang** [comment]
不好意思，我没能复现这个报错。初步猜测可能是由于Python与Tianshou版本不兼容，可以试试降级Python为3.7，或参考这个[Docker镜像](https://hub.docker.com/repository/docker/lizonghango00o1/agod/tags)中的软件环境。
